# Generated by Django 5.0.7 on 2024-07-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_lottery_customuser_credit_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='user/image/'),
        ),
    ]
