# Generated by Django 5.0.7 on 2024-09-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_lotterychance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterychance',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('finished', 'Finished')], default='pending', max_length=255),
        ),
    ]
