# Generated by Django 5.0.7 on 2024-09-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_footballapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
