# Generated by Django 5.0.7 on 2024-09-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league_round',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
