# Generated by Django 5.0.7 on 2024-09-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
