# Generated by Django 5.0.7 on 2024-09-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_match_is_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
