# Generated by Django 5.0.7 on 2024-09-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_leaguecheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguecheck',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='leaguecheck',
            name='date_field',
            field=models.DateField(default=None, null=True),
        ),
    ]
