# Generated by Django 5.0.7 on 2024-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_rename_date_leaguecheck_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateChecked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
