# Generated by Django 5.0.7 on 2024-10-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_apilog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeagueCheck',
        ),
    ]
